name: C/C++ CI

on:
  push:
    branches:
    - dev
    - features/*
    
  pull_request:
    branches:
    - master
    - dev

env:
  BUILD_TYPE: Release

jobs:
  setup: 
    name: Setting up the environment 
    runs-on: windows-latest
    
    steps:
      - name: Install Vulkan SDK
        run: curl "https://sdk.lunarg.com/sdk/download/1.3.211.0/windows/VulkanSDK-1.3.211.0-Installer.exe" -OutFile "C:\VulkanSDK-1.3.211.0-Installer.exe"
        shell: powershell
      
      - name: Setup Vulkan SDK
        run: |
          cd C:\
          start VulkanSDK-1.3.211.0-Installer.exe --accept-licenses --default-answer --confirm-command install
        shell: cmd
    
    
  build:
    name: CMake Build
    needs: setup
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
